version: '3.8'

services:
  django:
    build:
      image: diansregistry.azurecr.io/msediansapp-django:latest
      dockerfile: Dockerfile
    container_name: django_frontend_revised
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=django_frontend_revised,localhost
    depends_on:
      - flask

  flask:
    build:
      image: diansregistry.azurecr.io/msediansapp-flask:latest
      dockerfile: Dockerfile
    container_name: flask_backend_revised
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb+srv://marko_m:HhfpCcGObwf7Huxn@maincluster.zwq2b.mongodb.net/?retryWrites=true&w=majority&appName=MainCluster
